#!/bin/sh

case "$1" in
    # Load scull, module driver, modprobe
    start)
        echo "Loading modules"
        cd /usr/bin
        scull_load
        module_load faulty
        modprobe hello
        ;;
    stop)
        echo "Unloading modules"
        cd /usr/bin
        scull_unload
        rmmod hello
        module_unload faulty
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac
